config/routes.rb
Rails.application.routes.draw do  
  
  root 'pages#show'

  resources :tasks
  resources :posts
  
  resources :tickets do
    resources :notes
  end

  resources :companies
  devise_for :users, :controllers => { registrations: 'registrations' }

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	belongs_to :company
	belongs_to :user
	has_many	 :notes
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  def index
    @tickets = Ticket.all
  end

 
  def show
    @ticket = Ticket.find(params[:id])
    @past_notes = @ticket.notes.order('id DESC')
    @note = @ticket.notes.new
  end

  
  def new
    @ticket = Ticket.new
    # @companies = Company.all
  end

  # GET /tickets/1/edit
  def edit
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user_id = current_user.id

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:company_id, :title, :body)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<div class="row">
  <div class="col-md-4">    
  
    <%= form_for(@ticket, :html => { :class => "form-horizontal" } ) do |f| %>
      <%= f.label :title, 'Ticket subject' %>
      <%= f.text_field :title, class: 'form-control' %>
      
      <%= f.label :company_id %>
      <% companies_array = Company.all.map { |company| [company.title, company.id] } %>
      <%= f.select :company_id, options_for_select(companies_array), {}, {class: 'form-control'} %>
      <br>
      <%= f.submit "Submit ticket", class: 'form-control btn btn-primary' %>

  </div>
  <div class="col-md-8">

      <%= f.label :body %>
      <%= f.text_area :body, rows: 20, class: 'form-control' %> 

    <% end %>

  </div>
</div>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<div class="row">
  <div class="col-md-4">    
  
    <%= form_for(@ticket, :html => { :class => "form-horizontal" } ) do |f| %>
      <%= f.label :title, 'Ticket subject' %>
      <%= f.text_field :title, class: 'form-control' %>      
    
      <br>
      <%= f.submit "Submit ticket", class: 'form-control btn btn-primary' %>

  </div>
  <div class="col-md-8">

      <%= f.label :body %>
      <%= f.text_area :body, rows: 20, class: 'form-control' %> 

    <% end %>

  </div>
</div>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tickets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>      
      <tr>
        <td> <%= ticket.title %> -</td>
        <td><em><%= ticket.company.title %></em></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form' %>

<%= link_to '<- Return', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<h1><%= @ticket.title %> : Ticket # <%= @ticket.id %></h1>		

	<a href="#" id='new_note' class='btn btn-primary pull-right'>Add note</a>

	<em>
	<p><%= link_to @ticket.company.title, @ticket.company %> - Created <%= @ticket.created_at.strftime('%B %d, %Y at %l:%M %p') %></p>

	<% unless @ticket.created_at == @ticket.updated_at %>
		<p>Last updated at <%= @ticket.updated_at.strftime('%B %d, %Y at %l:%M %p') %></p>
	<% end %>
	<p>Ticket owned by: <%= @ticket.user.first_name %> <%= @ticket.user.last_name %></p>
	</em>

	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
		    	<h3 class="panel-title">Ticket description</h3>
		  	</div>
			
			<div class="panel-body">
				<%= @ticket.body %>
			</div>

			<div class="panel-footer">
				<%= link_to 'Edit', edit_ticket_path(@ticket), class: 'btn btn-sm btn-warning' %> |
				<%= link_to 'View all tickets', tickets_path, class: 'btn btn-sm btn-info' %>
			</div>
		</div>
	</div>	

	<div class="col-md-6">

	<%= form_for([@ticket, @note], html: { class: 'form-horizontal hidden', id: 'new_note_form' } ) do |f| %>
	  <div class="form-group">
	    <%= f.label :body %><br>
	    <%= f.text_field :body %>
	  </div>
	  <div class="form-group">
	    <%= f.submit %>
	  </div>
	<% end %>

	<% @past_notes.each do |note| %>
		<div class="panel panel-default">
			<div class="panel-heading">
		    	<h3 class="panel-title">Note made on <%= note.created_at.strftime('%B %d, %Y at %l:%M %p') %></h3>                        
		  	</div>

		  	<div class="panel-body">
		  		<p><%= note.body %></p>
		  	</div>


		</div>
	<% end %>
	</div>
</div>	

app/views/tickets/show.js.erb
$('new_note').click(function() {
	$(this).hide();
});